### ISSUE TITLE
Problem with order()

### ISSUE THREAD

**Issue by danyakov** [sjaakp/yii2-sortable-behavior#12]
Hello. First thank you for this script. It will be very useful for me.
But for this moment I have problem. I copy everything like in instruction. And sorting works, but with small problem when I need to sort not all records in table.
For example, I have records in one table:
id=1, relative_id=1, position=0
id=2, relative_id=1, position=1
id=3, relative_id=1, position=2
id=4, relative_id=2, position=0

And when I make sorting with selected items by relative_id=1, for example I want id=3 to be first in the list. I drag item to the top. All related records update. But also updates unrelated records. In the end I have:
id=1, relative_id=1, position=1
id=2, relative_id=1, position=2
id=3, relative_id=1, position=0
_id=4, relative_id=2, position=1_
But id=4 wasn't even selected from database to model.

I think, method order() works incorrect. But I can't find information about this method.
$this->findModel( $post['key'] )->**order**( $post['pos'] );   What order() does?

Thank you!

**Comment by mkraibt** [comment]
I got the same issue... any updates on this ??
